### ISSUE TITLE
No such file or directory: 'farsi_names.sql'

### ISSUE THREAD

**Issue by DsDastgheib** [language-ml/parsi.io#31]
Hi, 
I'm trying to use `QuestionGeneration` from `parsi_io.modules.question_generator` to make data containing some questions. But unfortunately, I'm facing the following error:

```
Traceback (most recent call last):
  File "make_farsi_question.py", line 7, in <module>
    extractor = QuestionGeneration()
  File "/home/myuser/.local/lib/python3.8/site-packages/parsi_io/modules/question_generator.py", line 195, in __init__
    self.utils = Utils(farsnet_user, farsnet_token)
  File "/home/myuser/.local/lib/python3.8/site-packages/parsi_io/modules/question_generator.py", line 26, in __init__
    self.names, self.places = self.load_files()
  File "/home/myuser/.local/lib/python3.8/site-packages/parsi_io/modules/question_generator.py", line 168, in load_files
    with open('farsi_names.sql') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'farsi_names.sql'
```

P. S.
I have installed parsi.io using the pip install git+https://github.com/language-ml/parsi.io.git instructed on the ReadMe page.

Thanks in advance

**Comment by kargaranamir** [comment]
It seems it needs [`farsi_names.sql`](https://github.com/language-ml/parsi.io/blob/91dd03b3195bd4d845c4f651d94e443f7dfd8a72/parsi_io/modules/question_generator.py#L168) file and [`places.txt`](https://github.com/language-ml/parsi.io/blob/91dd03b3195bd4d845c4f651d94e443f7dfd8a72/parsi_io/modules/question_generator.py#L171) file.

@SMesForoush Are these files missing?
